### ISSUE TITLE
Out of sync image (probably)

### ISSUE THREAD

**Issue by cipi1965** [navhaxs/AvaloniaNDI#1]
Hi!
I'm trying to port your work to crossplatform .NET (currently trying it on macOS).
It compiles and executes but the image seems out of sync via NDI Video Monitor.
Have you any idea on why it could happen?
Link to video: https://youtu.be/P-sLzI413gY

**Comment by cipi1965** [comment]
Update: it seems to solve if i put a black background (so it is an alpha problem with macOS?)

**Comment by navhaxs** [comment]
Hi @cipi1965 

Awesome to know that this can port over to macOS!

Yeah I can see why you suspect it is out of sync. I did find a frame in your video where it looks 'normal'

But as to the root issue, sorry this is a bit outside my domain knowledge :/ Perhaps you can debug the frames being generated from the Avalonia component rendering (before they get sent to NDI). If that is all good, this might be an issue with the NDI frames or how they are getting sent.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/5162718/199647311-2552baef-6fd5-4e6d-a09e-c7cc863fc4bb.png">

**Comment by cipi1965** [comment]
Hello @navhaxs 

A black background fixes the problem, i think there is a problem with pixel conversion?

**Comment by navhaxs** [comment]
Good news on this @cipi1965 (or anyone else who comes across this in future!)

I finally got my hands on a Mac machine and could reproduce. It's the order of RGBA colour bits that's different between the platforms.

Fix is to change this line to:

```
FourCC = NDIlib.FourCC_type_e.FourCC_type_RGBA,
```

https://github.com/navhaxs/AvaloniaNDI/blob/114937b32dc6fe103fc4b0b713caa598a98675c9/AvaloniaNDI/NDISendContainer.cs#L546
